version: '3.2'
services:
    las:
        image: registry.scontain.com:5050/sconecuratedimages/services:las-scone5.0.0
        devices:
         - "$DEVICE"
    python:
        image: hello
        devices:
         - "$DEVICE"
        command: sh -c "sleep 5; SCONE_VERSION=1 SCONE_LOG=7 SCONE_LAS_ADDR=las SCONE_HEAP=256M SCONE_CAS_ADDR=$SCONE_CAS_ADDR SCONE_CONFIG_ID=$SESSION/hello python"  
        depends_on:
         - las
        privileged: true
